Scoping modules into independent packages (#198)
* feat: building scoped modules

* feat: module builds

* feat: scope names

* feat: moving scripts closer to target

* feat: adding readmes

* feat: build and tests configuration

* chore: finish setup of github actions

* chore: aliases and setup

* chore: updated ci config + build issues

* chore: site build script

* chore: update readme

* chore: readme classification

* chore: build prepublishing

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -1,37 +1,33 @@
 aliases:
-  - &restore_test_cache
-    keys:
-      - test-{{ .Environment.PROJECT_CACHE_VERSION }}-{{ .Branch }}-{{ .Environment.CIRCLE_JOB }}-{{ checksum "package-lock.json" }}
-
-  - &save_test_cache
-    paths:
-      - ./node_modules
-    key: test-{{ .Environment.PROJECT_CACHE_VERSION }}-{{ .Branch }}-{{ .Environment.CIRCLE_JOB }}-{{ checksum "package-lock.json" }}
-
-  - &restore_release_cache
-    keys:
-      - release-{{ .Environment.PROJECT_CACHE_VERSION }}-{{ checksum "package-lock.json" }}
-
-  - &save_release_cache
-    paths:
-      - ./node_modules
-    key: release-{{ .Environment.PROJECT_CACHE_VERSION }}-{{ checksum "package-lock.json" }}
-
   - &install_npm
     name: install dependencies with extras
-    command: |
-      npm run setup
-
-  - &install_npm_node8
-    name: install dependencies
-    command: |
-      OTPLIB_SETUP_TYPE=node8 npm run setup
+    command: npm run setup
 
   - &build_package
     name: build package
+    command: npm run build
+
+  - &test_package
+    name: test
+    command: npm run test
+
+  - &lint_package
+    name: lint
+    command: npm run lint
+
+  - &upload_coverage
+    name: send coverage report
     command: |
-      npm run clean
-      npm run build
+      if [[ $CIRCLE_PROJECT_USERNAME == $PROJECT_OWNER_NAME ]]; then
+        {
+          npm run upload:coverage
+        } || {
+          echo "unable to update coverage."
+        }
+      else
+        echo "skipping coverage uploading."
+      fi
+    when: on_success
 
   - &filter_common
     branches:
@@ -57,18 +53,6 @@ aliases:
     branches:
       ignore: /.*/
 
-  - &node_tests
-    working_directory: ~/project
-    steps:
-      - checkout
-      - restore-cache: *restore_test_cache
-      - run: *install_npm
-      - save_cache: *save_test_cache
-      - run: *build_package
-      - run:
-          name: test
-          command: npm run test:module
-
   - &defaults
     working_directory: ~/project
     docker:
@@ -77,14 +61,8 @@ aliases:
   - &npm_publish
     steps:
       - checkout
-      - restore-cache: *restore_release_cache
       - run: *install_npm
-      - save_cache: *save_release_cache
-      - run:
-          name: build for npm
-          command: |
-            npm run clean
-            npm run build
+      - run: *build_package
       - run:
           working_directory: ~/project/builds/otplib
           name: publish to npm
@@ -108,50 +86,32 @@ aliases:
 version: 2
 jobs:
   node_v8:
+    working_directory: ~/project
     docker:
       - image: circleci/node:8
     steps:
       - checkout
-      - restore-cache: *restore_test_cache
-      - run: *install_npm_node8
-      - save_cache: *save_test_cache
-      - run: *build_package
       - run:
           name: test
-          command: npm run test:node8
+          command: npm run ci:node8
   node_v10:
     <<: *defaults
     steps:
       - checkout
-      - restore-cache: *restore_test_cache
       - run: *install_npm
-      - save_cache: *save_test_cache
-      - run: *build_package
-      - run:
-          name: test
-          command: npm run test:module
-      - run:
-          name: lint
-          command: |
-            npm run lint
-      - run:
-          name: send coverage report
-          command: |
-            if [[ $CIRCLE_PROJECT_USERNAME == $PROJECT_OWNER_NAME ]]; then
-              {
-                npm run upload:coverage
-              } || {
-                echo "unable to update coverage."
-              }
-            else
-              echo "skipping coverage uploading."
-            fi
-          when: on_success
+      - run: *test_package
+      - run: *lint_package
+      - run: *upload_coverage
 
   node_v12:
+    working_directory: ~/project
     docker:
       - image: circleci/node:12
-    <<: *node_tests
+    steps:
+      - checkout
+      - run: *install_npm
+      - run: *build_package
+      - run: *test_package
 
   publish_npm_stable:
     environment:
@@ -164,31 +124,6 @@ jobs:
       RUNTIME_NPM_TAG: next
     <<: *defaults
     <<: *npm_publish
-
-  deploy_website:
-    <<: *defaults
-    steps:
-      - checkout
-      - restore-cache: *restore_release_cache
-      - run: *install_npm
-      - save_cache: *save_release_cache
-      - run:
-          name: configure git user
-          command: |
-            git config --global user.email $PROJECT_DEPLOY_EMAIL
-            git config --global user.name $PROJECT_DEPLOY_NAME
-      - run:
-          working_directory: ~/project/site
-          name: deploying website
-          command: |
-            if [[ $CIRCLE_PROJECT_USERNAME == $PROJECT_OWNER_NAME && -z $CI_PULL_REQUEST && -z $CIRCLE_PR_USERNAME ]]; then
-              npm install
-              npm run build:deps
-              npm run build
-              npm run deploy
-            else
-              echo "skipping deploy."
-            fi
 
 workflows:
   version: 2
@@ -208,22 +143,16 @@ workflows:
           filters: *filter_tag_all
       - node_v12:
           filters: *filter_tag_all
-      - hold_website:
+      - hold_npm_beta:
           type: approval
           requires:
             - node_v8
             - node_v10
             - node_v12
-          filters: *filter_tag_stable
-      - deploy_website:
-          requires:
-            - hold_website
-          filters: *filter_tag_stable
+          filters: *filter_tag_beta
       - publish_npm_beta:
           requires:
-            - node_v8
-            - node_v10
-            - node_v12
+            - hold_npm_beta
           filters: *filter_tag_beta
       - hold_npm:
           type: approval
